name: XUnit test

on:
  push:
    branches:
      - "main"
      - "dev"
    pull_requests:

env:
  PROJECT_TESTS_PATH: 'src/PupaLib.Node.Tests/PupaLib.Node.Tests.csproj'

permissions:
  contents: read

jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: "Setup .NET 10"
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: "Cache Nuget"
        uses: actions/cache@v5
        with:
          path: ~/.nuget/pacakges
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}

      - name: "Resotre all projects in solution"
        run: dotnet restore

      - name: "Build all projects in solution"
        run: dotnet build --no-restore --configuration Release

      - name: "Run test"
        run: dotnet test ${{ env.PROJECT_TESTS_PATH }} --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=test-report.trx"

      - name: "Upload test report"
        uses: actions/upload-artifact@v7
        with:
          name: test-report
          path: '**/*.trx'