name: XUnit test & Deploy nuget package

on:
  push:
    tags:
      - 'v*'

env:
  PROJECT_LIB_PATH: 'src/PupaLib.Node/PupaLib.Node.csproj'
  PROJECT_TESTS_PATH: 'src/PupaLib.Node.Tests/PupaLib.Node.Tests.csproj'
  PACKAGE_OUTPUT_DIR: ${{ github.workspace }}/output
  OUTPUT_NUPKG_FILE: ${{ github.workspace }}/output/*.nupkg
  NUGET_SOURCE_URI: "https://api.nuget.org/v3/index.json"
  GITHUB_USERNAME: "Artpupser"
  
permissions:
  contents: read
  packages: write
  
jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: "Setup .NET 10"
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: "Cache Nuget"
        uses: actions/cache@v5
        with:
          path: ~/.nuget/pacakges
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}

      - name: "Resotre all projects in solution"
        run: dotnet restore

      - name: "Build all projects in solution"
        run: dotnet build --no-restore --configuration Release

      - name: "Run test"
        run: dotnet test ${{ env.PROJECT_TESTS_PATH }} --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=test-report.trx"

      - name: "Upload test report"
        uses: actions/upload-artifact@v7
        with:
          name: test-report
          path: '**/*.trx'
  deploy:
    name: "Deploy"
    runs-on: 'ubuntu-latest'
    needs: test
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: "Setup .NET 10"
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: "Cache Nuget"
        uses: actions/cache@v5
        with:
          path: ~/.nuget/pacakges
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}

      - name: "Restore package"
        run: dotnet restore ${{ env.PROJECT_LIB_PATH }}

      - name: "Build package"
        run: dotnet build ${{ env.PROJECT_LIB_PATH }} --no-restore --configuration Release

      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: "Pack pacakge"
        run: dotnet pack ${{ env.PROJECT_LIB_PATH }} --no-restore --no-build -c Release --include-symbols -p:PackageVersion=${{ env.VERSION }} --output ${{ env.PACKAGE_OUTPUT_DIR }}

      - name: "NuGet login (OIDC temp API key)"
        uses: NuGet/login@v1
        id: nuget-login
        with:
          user: ${{ env.GITHUB_USERNAME }}

      - name: "Push package NUGET"
        run: dotnet nuget push --skip-duplicate ${{ env.OUTPUT_NUPKG_FILE }} -k ${{ steps.nuget-login.outputs.NUGET_API_KEY }} -s ${{ env.NUGET_SOURCE_URI }}

      - name: "Add source for github"
        run: dotnet nuget add source --username ${{ env.GITHUB_USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ env.GITHUB_USERNAME }}/index.json"

      - name: "Push package GITHUB"
        run: dotnet nuget push --skip-duplicate ${{ env.OUTPUT_NUPKG_FILE }} -k ${{ secrets.GITHUB_TOKEN }} -s "github"